In [27]:
# Importação:

import pandas as pd
from topsoft.database import configure_database

In [28]:
# Cria o banco de dados e as tabelas necessárias (se ainda não existirem)

configure_database()

DADOS DOS ALUNOS

In [29]:
# Lendo arquivo de alunos (exportado pelo TopSoft) com os dados já recebidos da API da ActivitySoft:

# TODO: Force each column to be a specific type
df_activity = pd.read_json(
    "alunos.json",
    dtype={
        "cartao_acesso": "string",
        "celular": "string",
        "cpf": "string",
        "data_nascimento": "date",
        "email": "string",
        "filiacao_1_id": "int",
        "filiacao_2_id": "int",
        "foto_data_hora_alteracao": "date",
        "id": "int",
        "id_turmas": "string",
        "matricula": "string",
        "nome": "string",
        "responsaveis_adicionais_ids": "string",
        "responsavel_id": "int",
        "responsavel_secundario_id": "int",
        "sexo": "string",
        "tipo_liberacao": "string",
        "unidade_id": "int",
        "url_foto": "string",
    },
)

# Drop column id to not conflict with the database primary key:
df_activity.drop(columns=["id"], inplace=True, errors="ignore")

# Formatando os nomes para garantir que não excedam 40 caracteres e removendo espaços extras:
df_activity["nome"] = df_activity["nome"].apply(lambda x: x[0:40].strip())


# Strip all string columns to remove leading/trailing spaces:
def strip_string_columns(df):
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].str.strip()
    return df


df_activity = strip_string_columns(df_activity)

# Forçando as colunas de data para o formato correto:
df_activity["data_nascimento"] = pd.to_datetime(
    df_activity["data_nascimento"], errors="coerce"
).dt.date
df_activity["foto_data_hora_alteracao"] = pd.to_datetime(
    df_activity["foto_data_hora_alteracao"], errors="coerce"
).dt.date

# Ordenando o DataFrame por nome:
df_activity.sort_values(by="nome", inplace=True)
display(df_activity)

,cartao_acesso,celular,cpf,data_nascimento,email,filiacao_1_id,filiacao_2_id,foto_data_hora_alteracao,id_turmas,matricula,nome,responsaveis_adicionais_ids,responsavel_id,responsavel_secundario_id,sexo,tipo_liberacao,unidade_id,url_foto
68,<NA>,<NA>,10070897174,2019-04-15,<NA>,5463,5464.0,NaT,[16],91492,ABNER MATOS MORAIS,[],5464,None,M,<NA>,1,<NA>
284,<NA>,<NA>,<NA>,2010-06-30,<NA>,11372,11371.0,NaT,[30],91696,ADAM ANDRADE DO PRADO RODRIGUES,[],11372,None,M,<NA>,1,<NA>
174,<NA>,<NA>,09659459106,2018-11-05,<NA>,11379,3532.0,NaT,[1],91541,ADHARA MELO VALADÃO DE BRITO,[],3532,None,F,<NA>,1,<NA>
180,<NA>,61993602716,08726553180,2007-08-07,alanacrc08@gmail.com,4413,4411.0,NaT,[23],2924,ALANA CRISTINA RUFINO COSTA,[],4413,None,F,<NA>,1,<NA>
128,<NA>,<NA>,<NA>,2021-05-17,<NA>,11592,11591.0,NaT,[20],91925,ALEXANDRE ALVES SIQUEIRA DOS SANTOS,[],11592,None,M,<NA>,1,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,<NA>,<NA>,<NA>,2010-11-18,<NA>,1128,1126.0,NaT,[30],90519,YURI EMERICK SANTOS OLIVEIRA,[],1126,None,M,<NA>,1,<NA>
360,<NA>,<NA>,<NA>,2009-08-10,<NA>,2418,2421.0,NaT,"[21, 33, 35, 31, 34, 32]",91305,ÁLVARO CALAIS DOS REIS,[],2418,None,M,<NA>,1,<NA>
331,<NA>,<NA>,<NA>,2009-09-13,<NA>,1161,1129.0,NaT,[21],91344,ÂNGELO MÁXIMO DOS SANTOS D'AVILA CULAU,[],1129,None,M,<NA>,1,<NA>
70,<NA>,<NA>,<NA>,2010-06-05,angelovalderrama0506@gmail.com,1173,1171.0,NaT,[21],91433,ÂNGELO VALDERRAMA DA SILVA,[],1171,None,M,<NA>,1,<NA>
298,<NA>,<NA>,10796111189,2012-01-14,icarorico1@gmail.com,9679,9677.0,NaT,[28],91578,ÍCARO MARQUES DE ALMEIDA BEZERRA,[],9677,None,M,<NA>,1,<NA>

In [30]:
# UMA POSSÍVEL SOLUÇÃO PARA LER OS DADOS DO ALUNO DIRETAMENTE DO BANCO DE DADOS

# import sqlite3

# conn = sqlite3.connect('meu_banco.db')
# df_activity = pd.read_sql_table('minha_tabela', conn)

In [31]:
# Validando se não existem nomes duplicados:

if df_activity["nome"].duplicated().any():
    print("Existem nomes duplicados no DataFrame de alunos.")
    display(df_activity[df_activity["nome"].duplicated(keep=False)])

ARQUIVO BILHETES.TXT CONTENDO NUMERO DA CARTEIRINHA + NOME

In [32]:
# Lendo arquivo de carteirinhas (algum já pre-existente ou exportado pelo TopSoft):

with open(r"gi5_cartoes.txt", "r") as file:
    dados = file.read()

linhas = dados.split("\n")
carteirinhas = [{"cartao": i[0:16], "nome": i[16 : 16 + 40]} for i in linhas]

# Criando DataFrame de carteirinhas:
df_cartoes = pd.DataFrame(carteirinhas)

# Formatando os nomes para garantir que não excedam 40 caracteres e removendo espaços extras:
df_cartoes["nome"] = df_cartoes["nome"].apply(lambda x: x[0:40].strip())

# Drop empty names
df_cartoes = df_cartoes[df_cartoes["nome"] != ""]

# Ordenando o DataFrame por nome:
df_cartoes.sort_values(by="nome", inplace=True)
display(df_cartoes)

               cartao                                    nome
25   0000335012942875                   ADAILTON LINO LACERDA
325  0000335012575680         ADAM ANDRADE DO PRADO RODRIGUES
265  0000335014231779            ADHARA MELO VALADÃO DE BRITO
26   0000335013218034             ALANA CRISTINA RUFINO COSTA
354  0000335013217313            ALEXANDRE DA NÓBREGA MENEZES
..                ...                                     ...
89   0000335013266473            YURI EMERICK SANTOS OLIVEIRA
195  0000335013235094                  ÁLVARO CALAIS DOS REIS
204  0000335012234896  ÂNGELO MÁXIMO DOS SANTOS D'AVILA CULAU
231  0000335013276728              ÂNGELO VALDERRAMA DA SILVA
281  0000335012563598        ÍCARO MARQUES DE ALMEIDA BEZERRA

[489 rows x 2 columns]

In [33]:
# Validando se não existem nomes duplicados:


if df_cartoes["nome"].duplicated().any():


    print("Existem nomes duplicados no DataFrame de carteirinhas.")

    display(df_cartoes[df_cartoes["nome"].duplicated(keep=False)])

PRIMEIRO MERGE: TENTANDO VINCULAR CADA CARTEIRINHA A UM ALUNO

In [34]:
# Merge dos DataFrames para vincular cada carteirinha ao aluno correspondente (baseado no nome):

df_merged = pd.merge(df_activity, df_cartoes, left_on="nome", right_on="nome")
display(df_merged[["nome", "cartao", "matricula"]])

                                       nome            cartao matricula
0           ADAM ANDRADE DO PRADO RODRIGUES  0000335012575680     91696
1              ADHARA MELO VALADÃO DE BRITO  0000335014231779     91541
2               ALANA CRISTINA RUFINO COSTA  0000335013218034      2924
3              ALEXANDRE DA NÓBREGA MENEZES  0000335013217313     91760
4                   ALEXANDRE PORTELA SALES  0000335014255908     91961
..                                      ...               ...       ...
452            YURI EMERICK SANTOS OLIVEIRA  0000335013266473     90519
453                  ÁLVARO CALAIS DOS REIS  0000335013235094     91305
454  ÂNGELO MÁXIMO DOS SANTOS D'AVILA CULAU  0000335012234896     91344
455              ÂNGELO VALDERRAMA DA SILVA  0000335013276728     91433
456        ÍCARO MARQUES DE ALMEIDA BEZERRA  0000335012563598     91578

[457 rows x 3 columns]

In [35]:
# Vamos atualizar o Banco de Dados local com os dados do DataFrame:

from topsoft.repository import (
    bind_cartao_acesso_to_aluno,
    get_or_create_cartao_acesso,
    get_or_create_aluno,
)

for index, row in df_merged.iterrows():
    cartao_acesso = get_or_create_cartao_acesso(row["cartao"])

    # Convert row to dict and remove NaN values
    dict_row = row.to_dict()
    dict_row = {k: v for k, v in dict_row.items() if pd.notna(v)}
    dict_row = {k: v for k, v in dict_row.items() if v is not None}
    # TODO: We could drop NaN values directly in the DataFrame before iterating, but this is a quick fix.

    # Create or get the aluno, passing all row values as keyword arguments
    aluno = get_or_create_aluno(**dict_row)

    bind_cartao_acesso_to_aluno(
        cartao_acesso_id=cartao_acesso.id,
        aluno_id=aluno.id,
    )
    print(f"Cartão {cartao_acesso.numeracao} vinculado ao aluno {aluno.nome}.")

Cartão 0000335012575680 vinculado ao aluno ADAM ANDRADE DO PRADO RODRIGUES.
Cartão 0000335014231779 vinculado ao aluno ADHARA MELO VALADÃO DE BRITO.
Cartão 0000335013218034 vinculado ao aluno ALANA CRISTINA RUFINO COSTA.
Cartão 0000335013217313 vinculado ao aluno ALEXANDRE DA NÓBREGA MENEZES.
Cartão 0000335014255908 vinculado ao aluno ALEXANDRE PORTELA SALES.
Cartão 0000313533370954 vinculado ao aluno ALICE ANDRADE LEITE DE ALMEIDA.
Cartão 0000335013048336 vinculado ao aluno ALICE BRAGA CARVALHO NOVAIS.
Cartão 0000313534531316 vinculado ao aluno ALICE DE LACERDA BENVENTO.
Cartão 0000335012636754 vinculado ao aluno ALICE PAYÃO PEREIRA.
Cartão 0000335012199133 vinculado ao aluno ALVARO AUGUSTO DE TOLEDO.
Cartão 0000335012105115 vinculado ao aluno ALYSSON ALVES GEBRIM DE MORAIS.
Cartão 0000335012967367 vinculado ao aluno ALÍCIA DE JESUS RAMOS.
Cartão 0000335012605018 vinculado ao aluno AMANDA BARRETO GALLETTI QUINDERÉ.
Cartão 0000335012630414 vinculado ao aluno ANA BEATRIZ DE JESUS QUEIROZ.
Cartão 0000335012625177 vinculado ao aluno ANA BEATRIZ FERREIRA CONTI.
Cartão 0000335012640137 vinculado ao aluno ANA BEATRIZ PACHECO SERAFIM.
Cartão 0000335013218797 vinculado ao aluno ANA CAROLINA SOARES ALENCAR.
Cartão 0000335012590526 vinculado ao aluno ANA CAROLLINA MORENO NAVARRO VIDAL BRITO.
Cartão 0000335014317665 vinculado ao aluno ANA CECÍLIA XAVIER ALVES.
Cartão 0000335012597635 vinculado ao aluno ANA CLARA CARMO SOUTO.
Cartão 0000335012583041 vinculado ao aluno ANA CLARA DE OLIVEIRA PONTIERI.
Cartão 0000313534544128 vinculado ao aluno ANA CLARA INACIO BORGES DOS SANTOS.
Cartão 0000313534097032 vinculado ao aluno ANA CLARA RIBEIRO DOS SANTOS ROCHA.
Cartão 0000335012951321 vinculado ao aluno ANA CLARA SANTOS DA ROCHA.
Cartão 0000335013282626 vinculado ao aluno ANA JULIA PEREIRA DE LARA.
Cartão 0000335012236770 vinculado ao aluno ANA LARA DAVID SANTOS.
Cartão 0000335013211228 vinculado ao aluno ANA LUÍSA RODRIGUES LOPES.
Cartão 0000335012197545 vinculado ao aluno ANA PAULA NOGUEIRA FIALHO.
Cartão 0000335012609218 vinculado ao aluno ANA SOUZA BRITO.
Cartão 0000335013908171 vinculado ao aluno ANDRESSA ARAÚJO SAMPAIO MEIRELES.
Cartão 0000335012625443 vinculado ao aluno ANDRÉ MOTA GUIMARAES NOBRE.
Cartão 0000335012237616 vinculado ao aluno ANGELINA MARINHO DOURADO VALENÇA.
Cartão 0000335013246242 vinculado ao aluno ANNA CLARA DOS REIS BONTEMPO.
Cartão 0000335012265116 vinculado ao aluno ANNA GABRIELA FELIPE COELHO.
Cartão 0000335012639211 vinculado ao aluno ANNA LUIZA VIEIRA GUEDES.
Cartão 0000335012626916 vinculado ao aluno ANNY GABRIELLI DE SOUZA BRITO.
Cartão 0000335013945016 vinculado ao aluno ANTONIO SANTANA DE ALCANTARA.
Cartão 0000313534052578 vinculado ao aluno ARTHUR ALVES PEREIRA.
Cartão 0000335012641733 vinculado ao aluno ARTHUR BARBOSA DE SOUSA MELO.
Cartão 0000335013005294 vinculado ao aluno ARTHUR CAETANO BATISTA.
Cartão 0000335013257706 vinculado ao aluno ARTHUR DAVI DE CARVALHO FERREIRA.
Cartão 0000335012601929 vinculado ao aluno ARTHUR DE AQUINO CARDOSO.
Cartão 0000335013920533 vinculado ao aluno ARTHUR GABRIEL SOARES RIBEIRO.
Cartão 0000335014297149 vinculado ao aluno ARTHUR LEMOS FREITAS DA SILVA.
Cartão 0000335012982021 vinculado ao aluno ARTHUR QUEIROZ DE ASSIS.
Cartão 0000335012569216 vinculado ao aluno ARTHUR QUEIROZ DE AZEVEDO.
Cartão 0000335012570725 vinculado ao aluno ARTHUR YUJI HIEDA DE MELO.
Cartão 0000335014269682 vinculado ao aluno ARTUR MIGUEL FRANCOLINO BEZERRA.
Cartão 0000335012935301 vinculado ao aluno ARTUR VALERIANO TABOSA.
Cartão 0000335012559431 vinculado ao aluno AYLA VAZ GOUVEA.
Cartão 0000335013068341 vinculado ao aluno BEATRIZ DE FREITAS TAMEIRÃO CASTELO BRAN.
Cartão 0000335012220286 vinculado ao aluno BEATRIZ LEAL COSTA.
Cartão 0000335012581855 vinculado ao aluno BEATRIZ REZENDE PEREIRA.
Cartão 0000335012112913 vinculado ao aluno BELLA CORSINO VITORINO CABRAL.
Cartão 0000335012618006 vinculado ao aluno BENJAMIM PEDROSA DA SILVA CAETANO.
Cartão 0000335012235324 vinculado ao aluno BENJAMIN ISMAEL DE ARAÚJO.
Cartão 0000335013942130 vinculado ao aluno BENJAMIN RAVENA COELHO LOPES.
Cartão 0000313533842568 vinculado ao aluno BENTO KOJI SATO MARIZ.
Cartão 0000335013215895 vinculado ao aluno BENÍCIO DJUROVIC COSTA.
Cartão 0000335012982405 vinculado ao aluno BENÍCIO LOPES SILVA.
Cartão 0000335014312647 vinculado ao aluno BENÍCIO RODRIGUES DE FREITAS.
Cartão 0000335012933691 vinculado ao aluno BERNARDO ALVES MENDES.
Cartão 0000335013222850 vinculado ao aluno BERNARDO COSTA PRUCOLI.
Cartão 0000335013234277 vinculado ao aluno BERNARDO SANTANA DE ALCANTARA.
Cartão 0000335012647761 vinculado ao aluno BERNARDO SANTIAGO BRAGA.
Cartão 0000335012571008 vinculado ao aluno BERNARDO SARKIS PACHECO.
Cartão 0000335013240817 vinculado ao aluno BIANCA BORGES SANTANA.
Cartão 0000335012976962 vinculado ao aluno BIANCA LUCENA DO NASCIMENTO.
Cartão 0000335013874329 vinculado ao aluno BRUNA GOMES CAMILLO.
Cartão 0000335012632728 vinculado ao aluno BRUNA TULUX CORREIA.
Cartão 0000335014245550 vinculado ao aluno CAIO HENRIQUE SANTOS DA ROCHA.
Cartão 0000335013248425 vinculado ao aluno CAIO RIBOLA PELEGRINI.
Cartão 0000313534030593 vinculado ao aluno CALEBE GODOI DINIZ DE MOURA.
Cartão 0000335012198270 vinculado ao aluno CALEBE MELO VALADÃO DE BRITO.
Cartão 0000335012234295 vinculado ao aluno CAMILA ALVES BENVINDO.
Cartão 0000335013899299 vinculado ao aluno CAMILA ROSA RAMOS.
Cartão 0000335013264514 vinculado ao aluno CAMILLY ALMEIDA DE ANDRADE.
Cartão 0000335013288680 vinculado ao aluno CARLOS EDUARDO DE ARAUJO MARCOLINO.
Cartão 0000335012571724 vinculado ao aluno CAROLINA BARRETO GALLETTI QUINDERÉ.
Cartão 0000335012200188 vinculado ao aluno CATARINA ALVES CAMPOS.
Cartão 0000335012962963 vinculado ao aluno CATARINA FONSECA OSÓRIO.
Cartão 0000335012225168 vinculado ao aluno CATARINA SOUSA ARANTES.
Cartão 0000335014279110 vinculado ao aluno CAUÃ BRANDÃO DIAS.
Cartão 0000335013878671 vinculado ao aluno CAUÃ GAEL FERREIRA SOUSA.
Cartão 0000313534068923 vinculado ao aluno CAUÃ VITO RODRIGUES DOS SANTOS.
Cartão 0000335012593569 vinculado ao aluno CECILIA DOS SANTOS CASSIMIRO.
Cartão 0000335012257364 vinculado ao aluno CECILIA SAAVEDRA MAGALHÃES ANDRADE.
Cartão 0000335014248975 vinculado ao aluno CECÍLIA GOMES CONEGUNDES.
Cartão 0000335013007532 vinculado ao aluno CECÍLIA VALERIANO TABOSA.
Cartão 0000335012225455 vinculado ao aluno CHLOE LOUISE DE CARVALHO NEY.
Cartão 0000335012634322 vinculado ao aluno CHLOÉ VALDERRAMA DA SILVA.
Cartão 0000335012995486 vinculado ao aluno CLARA BATISTA XAVIER DOS SANTOS.
Cartão 0000335013207573 vinculado ao aluno CLARA BEATRIZ FERREIRA SOUSA.
Cartão 0000335013921142 vinculado ao aluno CLARA DE SANTANA MARTINS.
Cartão 0000335013861758 vinculado ao aluno CLARA MACHADO PIRES.
Cartão 0000335012228749 vinculado ao aluno DANIEL BANDEIRA DA SILVA.
Cartão 0000335012624515 vinculado ao aluno DANIEL SOUSA OLIVEIRA.
Cartão 0000335013208950 vinculado ao aluno DANIEL VIEIRA SOUZA.
Cartão 0000335012582069 vinculado ao aluno DAVI ALVES VALADÃO.
Cartão 0000335013042570 vinculado ao aluno DAVI BORGES DE BRITO.
Cartão 0000335012633039 vinculado ao aluno DAVI COSTA VALE MEIRELES.
Cartão 0000335013872196 vinculado ao aluno DAVI DE CASTRO CABRAL.
Cartão 0000335012250798 vinculado ao aluno DAVI FERRAZ PIRANGI.
Cartão 0000313534530689 vinculado ao aluno DAVI ISAC LEITE GONÇALVES.
Cartão 0000313534100031 vinculado ao aluno DAVI LEONARDO DE ARAUJO CAMARGOS.
Cartão 0000313534084864 vinculado ao aluno DAVI LEÃO DEOLINDO.
Cartão 0000313534067070 vinculado ao aluno DAVI LUCAS DE OLIVEIRA COSTA.
Cartão 0000335013250632 vinculado ao aluno DAVI LUCCA ALMEIDA DUARTE.
Cartão 0000335013938278 vinculado ao aluno DAVI MENDES MAFFON.
Cartão 0000335013003547 vinculado ao aluno DAVI OLIVEIRA ALVES DE SOUZA.
Cartão 0000335012603508 vinculado ao aluno DAVI RODRIGUES DE OLIVEIRA.
Cartão 0000335013282654 vinculado ao aluno DAVI RUI SOUTO DE CARVALHO.
Cartão 0000335014317816 vinculado ao aluno DAVI SOUZA MELO.
Cartão 0000335013232610 vinculado ao aluno DAVI VICTOR PRADO CAMPECHE.
Cartão 0000335013208112 vinculado ao aluno DAVID OLIVEIRA MARQUES.
Cartão 0000335013280189 vinculado ao aluno DIEGO CAVALCANTE SOARES.
Cartão 0000335012994800 vinculado ao aluno DIEGO SILVA FERREIRA.
Cartão 0000335014237426 vinculado ao aluno DIOGO DE PAULA NOVAIS.
Cartão 0000335013108113 vinculado ao aluno DÉBORA ALVES ZACARIAS DE MORAIS.
Cartão 0000335012633666 vinculado ao aluno DÉBORA SOUZA MORAES.
Cartão 0000335013920069 vinculado ao aluno EDUARDA ALMEIDA DA SILVA.
Cartão 0000335012253421 vinculado ao aluno EDUARDO SANTOS OLIVEIRA.
Cartão 0000335012930415 vinculado ao aluno EITOR  DE LIMA FARIAS.
Cartão 0000335012643433 vinculado ao aluno ELISA ANDRADE RESENDE.
Cartão 0000335013937330 vinculado ao aluno EMANUEL ASAFE ASSAD DE CASTRO.
Cartão 0000335012272577 vinculado ao aluno EMANUEL NORONHA DOS REIS.
Cartão 0000335012645231 vinculado ao aluno EMANUELE MOTA GUIMARÃES NOBRE.
Cartão 0000335013234156 vinculado ao aluno EMANUELLY DE OLIVEIRA COSTA.
Cartão 0000335012242145 vinculado ao aluno EMILLY REBECA MESSIAS LOPES.
Cartão 0000335013292517 vinculado ao aluno EMILY SOUZA RAAD.
Cartão 0000335013277400 vinculado ao aluno ENZO GABRIEL TAVARES.
Cartão 0000335012968475 vinculado ao aluno ENZO MORENO SILVA BRITO.
Cartão 0000335013000960 vinculado ao aluno ENZO VAZ GOUVEA.
Cartão 0000335013262298 vinculado ao aluno ESTELA MOURA DA SILVA.
Cartão 0000335013267063 vinculado ao aluno ESTER ESTEVAM DA SILVA MENDES.
Cartão 0000335012565851 vinculado ao aluno ESTER MARINHO CARDOSO.
Cartão 0000335012998382 vinculado ao aluno ESTHEFANY CHRISTI  ASSIS  MORAES.
Cartão 0000335012265140 vinculado ao aluno ESTHER AIRES DE SANTANA FONTENELE.
Cartão 0000335012617396 vinculado ao aluno ESTHER DE OLIVEIRA ALMEIDA.
Cartão 0000335013054746 vinculado ao aluno EVELLYN ALVES GEBRIM DE MORAIS.
Cartão 0000335013256153 vinculado ao aluno FELIPE COSTA RODRIGUES.
Cartão 0000335012970879 vinculado ao aluno FELIPE RIBEIRO LUSTOSA.
Cartão 0000335013268862 vinculado ao aluno FERNANDA LOPES CARNEIRO PEREIRA.
Cartão 0000335012940801 vinculado ao aluno FERNANDA LUIZA ROSSI DA SILVA.
Cartão 0000335013926612 vinculado ao aluno FERNANDA RIBEIRO LUSTOSA.
Cartão 0000335013240400 vinculado ao aluno FERNANDA SOUZA GUERRA.
Cartão 0000335012971934 vinculado ao aluno GABRIEL BORGES SANTANA.
Cartão 0000335012575340 vinculado ao aluno GABRIEL CLAUDIO DA SILVA SANTOS.
Cartão 0000313534600685 vinculado ao aluno GABRIEL FERREIRA GONÇALVES DA COSTA.
Cartão 0000335012587514 vinculado ao aluno GABRIEL LOPES RIBEIRO.
Cartão 0000335013006797 vinculado ao aluno GABRIEL MARTINS DE MOURA.
Cartão 0000335013279664 vinculado ao aluno GABRIEL SILVA DE SOUSA.
Cartão 0000335013248683 vinculado ao aluno GABRIELA SOFIA NUNES DA SILVA.
Cartão 0000335013059309 vinculado ao aluno GABRIELLA ARAUJO DE OLIVEIRA.
Cartão 0000335013280472 vinculado ao aluno GAEL SANDOVAL DIAS.
Cartão 0000335014287976 vinculado ao aluno GEOVANNA CRISTINA SOARES LORENZI.
Cartão 0000335012274715 vinculado ao aluno GEOVANNA DE BRITO ARAUJO.
Cartão 0000335012269027 vinculado ao aluno GEOVANNA LEITE SANTANA.
Cartão 0000335012946337 vinculado ao aluno GIDEÃO BENAIA MEIRELES SILVA DE AQUINO.
Cartão 0000313534552759 vinculado ao aluno GIOVANA FERREIRA BRITO  DA VITORIA.
Cartão 0000335012220390 vinculado ao aluno GIOVANNA LOUISE ALVES ARAÚJO.
Cartão 0000335012201927 vinculado ao aluno GIOVANNA TORRES XAVIER.
Cartão 0000335012578346 vinculado ao aluno GUILHERME ALARCÃO SOARES.
Cartão 0000335012227023 vinculado ao aluno GUILHERME CAMPOS FERREIRA.
Cartão 0000335012595436 vinculado ao aluno GUILHERME CASTRO DA COSTA LOPES NUNES.
Cartão 0000335013927586 vinculado ao aluno GUILHERME FONSECA PORFIRIO DA SILVA.
Cartão 0000335012997129 vinculado ao aluno GUSTAVO DE CASTRO CABRAL.
Cartão 0000335014299396 vinculado ao aluno HADASSA DE CERQUEIRA ORNELAS.
Cartão 0000335012604360 vinculado ao aluno HADASSA DIAS BARBOSA.
Cartão 0000335012933601 vinculado ao aluno HEITOR BARBOSA DE SOUSA MELO.
Cartão 0000335012639703 vinculado ao aluno HEITOR GABRIEL MARTINS FERREIRA DA SILVA.
Cartão 0000335012572171 vinculado ao aluno HEITOR GONÇALVES FARIA.
Cartão 0000335013011161 vinculado ao aluno HEITOR LIMA COLARES.
Cartão 0000335014248714 vinculado ao aluno HEITOR SILVA SANTOS ARAUJO.
Cartão 0000313533993650 vinculado ao aluno HELENA ALVES DE SIQUEIRA MARINHO.
Cartão 0000335012641283 vinculado ao aluno HELENA MACHADO OLIVEIRA CORRÊA.
Cartão 0000335013062863 vinculado ao aluno HELENA MUNOZ BRASIL.
Cartão 0000313533801772 vinculado ao aluno HELLEN HITOMI LISBÔA YAMADA.
Cartão 0000335012599508 vinculado ao aluno HELLENA TENORIO FARIAS FERREIRA BALBINO.
Cartão 0000335013281953 vinculado ao aluno HELOISA PEREIRA VIEIRA.
Cartão 0000335012992855 vinculado ao aluno HELOYSA MAYER REBOUÇAS DOS ANJOS.
Cartão 0000335012638572 vinculado ao aluno HELOÍSA NOVAIS FERNANDES.
Cartão 0000335012978208 vinculado ao aluno HELOÍSA SOARES DOMINGUES.
Cartão 0000313534553479 vinculado ao aluno HENRIQUE NEIFE NUNES MACHADO.
Cartão 0000335012618953 vinculado ao aluno HENRIQUE NOBRE DE BRITO.
Cartão 0000335013011439 vinculado ao aluno HENRY PIETRO MESSIAS ASSAD.
Cartão 0000335012111412 vinculado ao aluno ISAAC VICENTE RUDRIGUES DE LIMA.
Cartão 0000335012622168 vinculado ao aluno ISABEL CARDOSO MARQUES DAS NEVES.
Cartão 0000335012634891 vinculado ao aluno ISABELA GUEDES VENÂNCIO.
Cartão 0000335012184593 vinculado ao aluno ISABELA SALES VIVEIROS CARDOSO.
Cartão 0000335013268794 vinculado ao aluno ISABELLA CARVALHO ARAÚJO.
Cartão 0000313533439136 vinculado ao aluno ISABELLA GONÇALVES BANDEIRA.
Cartão 0000335013036149 vinculado ao aluno ISABELLA LIARTE LOIOLA DA CRUZ.
Cartão 0000313534544129 vinculado ao aluno ISABELLA LIMA DE SOUZA.
Cartão 0000335014243234 vinculado ao aluno ISABELLA SANTOS OTONI.
Cartão 0000335013941758 vinculado ao aluno ISABELLA TEIXEIRA COSTA.
Cartão 0000313534598523 vinculado ao aluno ISABELLE ARAUJO GONÇALVES.
Cartão 0000335012193509 vinculado ao aluno ISABELLE LOUISE BORGES ARAÚJO.
Cartão 0000335012268991 vinculado ao aluno ISADORA BANDEIRA DA SILVA.
Cartão 0000335012141095 vinculado ao aluno ISADORA CIRINO ALENCAR.
Cartão 0000335012202703 vinculado ao aluno ISADORA MONTEIRO DE MELO.
Cartão 0000335012587463 vinculado ao aluno ISADORA PEREIRA DE LARA.
Cartão 0000335012996969 vinculado ao aluno ISAQUE TIAGO DE OLIVEIRA VALENTE.
Cartão 0000335013858439 vinculado ao aluno ISIS REIS DE ALMEIDA.
Cartão 0000335013212987 vinculado ao aluno ISMAEL LUIZ VALADÃO FILHO.
Cartão 0000335013938909 vinculado ao aluno JOAO VICTOR TASSI TOSTES ALVES.
Cartão 0000335012197832 vinculado ao aluno JORGE DOS SANTOS BRAZ.
Cartão 0000335012579546 vinculado ao aluno JOYCE NUNES MELO.
Cartão 0000335012600374 vinculado ao aluno JOÃO EDUARDO QUINTINO MIRANDA.
Cartão 0000313533823127 vinculado ao aluno JOÃO GUILHERME MENDES SILVA.
Cartão 0000335013245203 vinculado ao aluno JOÃO HENRIQUE DANTAS ALBUQUERQUE.
Cartão 0000335013071926 vinculado ao aluno JOÃO LUCAS CARACAS AQUINO.
Cartão 0000335012619526 vinculado ao aluno JOÃO LUCAS DE OLIVEIRA ALVES.
Cartão 0000335012563982 vinculado ao aluno JOÃO LUIZ SILVA RIBEIRO.
Cartão 0000335014227639 vinculado ao aluno JOÃO MIGUEL RODRIGUES RIBEIRO.
Cartão 0000335013280524 vinculado ao aluno JOÃO PEDRO ARAUJO SILVA.
Cartão 0000335013931903 vinculado ao aluno JOÃO PEDRO TORRES CARNEIRO.
Cartão 0000335013013537 vinculado ao aluno JOÃO VICTOR ARNALDO FONSECA.
Cartão 0000335012938373 vinculado ao aluno JOÃO VITOR QUEIROZ DE ASSIS.
Cartão 0000335012599117 vinculado ao aluno JOÃO VÍTOR SOUZA MELO.
Cartão 0000335012563184 vinculado ao aluno JULIA BORGES BAKLIZI.
Cartão 0000335012643077 vinculado ao aluno JÚLIA ALVES ZACARIAS DE MORAIS.
Cartão 0000335012194564 vinculado ao aluno JÚLIA ARAUJO DE OLIVEIRA.
Cartão 0000335012272324 vinculado ao aluno JÚLIA CARVALHO RODRIGUES.
Cartão 0000335014283182 vinculado ao aluno JÚLIA DE ARAÚJO GARCEZ.
Cartão 0000335012223884 vinculado ao aluno JÚLIA NUNES PASSOS PINHEIRO.
Cartão 0000335012961819 vinculado ao aluno JÚLIO CÉSAR BORGES DE MOURA.
Cartão 0000335012265528 vinculado ao aluno KAMILLY DOS SANTOS MULLER.
Cartão 0000335012993920 vinculado ao aluno KATARINA ALARCÃO SOARES.
Cartão 0000335012989516 vinculado ao aluno KATHARINE BRITO ANDRADE LUSTOSA DE QUEIR.
Cartão 0000335014233708 vinculado ao aluno KAUAN HENRIQUE LUIZ SOL.
Cartão 0000335012959343 vinculado ao aluno KAUÃ EDUARDO ALVES DE MELO.
Cartão 0000313533437155 vinculado ao aluno KETLYN VITÓRIA DA SILVA DIAS.
Cartão 0000335012585718 vinculado ao aluno KEVIN ALVES PEREIRA NETO.
Cartão 0000335012255917 vinculado ao aluno LARA MANUELA DA COSTA VALE.
Cartão 0000335014318884 vinculado ao aluno LARA MOHAB MOHAMAD ALI.
Cartão 0000335013856061 vinculado ao aluno LARA SOUZA CAMBRAIA.
Cartão 0000335012600757 vinculado ao aluno LARISSA FERREIRA XAVIER.
Cartão 0000335013005366 vinculado ao aluno LAURA CALAIS DOS REIS.
Cartão 0000335013232844 vinculado ao aluno LAURA MIKAELLA BIZERAY DE AQUINO.
Cartão 0000335012181567 vinculado ao aluno LAURA MONTALVÃO FERREIRA RIBEIRO.
Cartão 0000335013218613 vinculado ao aluno LAURA RIBEIRO COSTA.
Cartão 0000335012626881 vinculado ao aluno LAURA SATO WATANABE.
Cartão 0000335012566539 vinculado ao aluno LAVINIA RODRIGUES DE MORAES.
Cartão 0000335012189720 vinculado ao aluno LAVÍNIA ALVES CAVALCANTE.
Cartão 0000335013273833 vinculado ao aluno LAYSA HELEN DE OLIVEIRA TEIXEIRA.
Cartão 0000335012568415 vinculado ao aluno LAYSLA KAUANE IBALDE RAMOS.
Cartão 0000335012211259 vinculado ao aluno LAÍS PONCIANO NOVAIS.
Cartão 0000335014243780 vinculado ao aluno LETICIA AMORIM PÁDUA.
Cartão 0000335012208660 vinculado ao aluno LETICIA MARTINS DE MOURA.
Cartão 0000335013014505 vinculado ao aluno LETICIA SOARES DOMINGUES.
Cartão 0000335012237145 vinculado ao aluno LETÍCIA RODRIGUES DA SILVA.
Cartão 0000335013249126 vinculado ao aluno LETÍCIA VENÂNCIO GOMES.
Cartão 0000335012950355 vinculado ao aluno LIVIA CASTRO DO MONTE.
Cartão 0000335013266002 vinculado ao aluno LIVIA CAVALCANTE MACEDO CAMARGOS.
Cartão 0000335013880459 vinculado ao aluno LIVIA FARIA LIBERATO.
Cartão 0000335013250449 vinculado ao aluno LOHAN MARRA LIMA.
Cartão 0000335013054447 vinculado ao aluno LORENZO MARQUES BARBOSA.
Cartão 0000335012617899 vinculado ao aluno LORENZO NOBRE D' ALCANTARA E SILVA.
Cartão 0000335013926228 vinculado ao aluno LORRAYNE GABRIELE DA COSTA CASTRO.
Cartão 0000335012582443 vinculado ao aluno LUAN DE AZEVEDO REGIS BIZERRA.
Cartão 0000335013865394 vinculado ao aluno LUCAS ANTÔNIO BORGES PEREIRA.
Cartão 0000335013220460 vinculado ao aluno LUCAS BERNARDES CARNEIRO.
Cartão 0000335012634835 vinculado ao aluno LUCAS DE AQUINO CONFORTE.
Cartão 0000335012144354 vinculado ao aluno LUCAS FREIRE DE SOUSA.
Cartão 0000335013285961 vinculado ao aluno LUCAS GABRIEL DE BRITO FREITAS.
Cartão 0000335012974843 vinculado ao aluno LUCAS GABRIEL NASCIMENTO DO CARMO.
Cartão 0000335013882744 vinculado ao aluno LUCAS GONÇALVES BANDEIRA.
Cartão 0000335012627323 vinculado ao aluno LUCAS LEÃO DEOLINDO.
Cartão 0000335012567680 vinculado ao aluno LUIGI LUCINDO LIMA.
Cartão 0000335012636392 vinculado ao aluno LUISA PRADO CAMPECHE.
Cartão 0000335012198579 vinculado ao aluno LUIZA OLIVEIRA NOBRE.
Cartão 0000313533376740 vinculado ao aluno LUÍS FELIPE DE ANDRADE SILVA.
Cartão 0000335013247829 vinculado ao aluno LUÍS HENRIQUE BERNARDES MARTINS.
Cartão 0000335013107100 vinculado ao aluno LUÍSA MONTALVÃO FERREIRA RIBEIRO.
Cartão 0000335012941134 vinculado ao aluno LUÍSA VICTÓRIA NUNES DANIEL.
Cartão 0000335014237147 vinculado ao aluno LUÍZA DOMIENSE ALVES.
Cartão 0000335012557770 vinculado ao aluno LUÍZA SOARES GOMES CANUTO.
Cartão 0000335012628880 vinculado ao aluno MAHRAN MOSAB MOHAMMAD NASSER.
Cartão 0000335012144729 vinculado ao aluno MAITÊ HILÁRIO REINERT.
Cartão 0000335013245332 vinculado ao aluno MANUELA ASSUNCAO CASTRO SILVA.
Cartão 0000335012260614 vinculado ao aluno MANUELA BORGES DE LISBOA.
Cartão 0000335012939934 vinculado ao aluno MANUELA GONÇALVES ANCHIÊTA.

SEGUNDO MERGE: CRIAR SUPOSTOS ALUNOS (POSSIVELMENTE FUNCIONÁRIOS) QUE ESTÃO PRESENTES NOS DADOS DA CATRACAS, MAS POR ALGUM MOTIVO NÃO ESTÃO NA LISTA COM OS DADOS DOS ALUNOS.

In [36]:
# Também será necessário criar "alunos" para as carteirinhas que não possuem aluno correspondente (ainda), possivelmente é um funcionário...

not_aluno_df = df_cartoes[~df_cartoes["nome"].isin(df_activity["nome"])]
not_aluno_df = not_aluno_df.copy()
not_aluno_df["matricula"] = not_aluno_df["cartao"].apply(lambda x: f"cartao_{x}")
display(not_aluno_df[["nome", "cartao", "matricula"]])

,nome,cartao,matricula
25,ADAILTON LINO LACERDA,0000335012942875,cartao_0000335012942875
20,ANDREIA RODRIGUES DA SILVA,0000038663884438,cartao_0000038663884438
3,ANDRÉA MARTINS DE OLIVEIRA,0000004307303760,cartao_0000004307303760
0,CÁSSIO SILVA FERREIRA,0000038663884449,cartao_0000038663884449
17,DANILO DA PENHA E SILVA,0000038659043912,cartao_0000038659043912
4,DEUZELICE PEREIRA DE MATOS,0000038663901480,cartao_0000038663901480
73,EDUARDA SILVA SANTOS,0000124556796581,cartao_0000124556796581
24,GIOVANNA DE JESUS SANTOS,0000004307304444,cartao_0000004307304444
5,IDELMA CARVALHO NOBRE DA SILVA,0000446682931338,cartao_0000446682931338
6,IVANI VICENTE DA SILVA,0000038659047246,cartao_0000038659047246
19,JORDANA BARRETO GALLETTI,0000038659047261,cartao_0000038659047261
7,JOSEFA DE CARVALHO NOBRE,0000038658961692,cartao_0000038658961692
1,KAMILA DE JESUS SANTOS,0000038658961867,cartao_0000038658961867
18,LUCIANA INÁCIO AMORIM DE ARAUJO,0000004307551553,cartao_0000004307551553
485,LUIZ OTAVIO GARCIA SOARES,0000355014297670,cartao_0000355014297670
8,MARCELA MOREIRA DE AGUIAR,0000038663969990,cartao_0000038663969990
11,MARIA DO SOCORRO ANTUNES MUDESTO,0000369374783691,cartao_0000369374783691
23,MARIA DOMINGAS DE FATIMA,0000038660412590,cartao_0000038660412590
9,MARIA GLORIA OLIVEIRA COSTA,0000335012974439,cartao_0000335012974439
10,MARIA GUIOMAR DURÃES PORTO,0000038663880708,cartao_0000038663880708
2,PATRÍCIA PAIXÃO COIMBRA,0000038663897502,cartao_0000038663897502
21,RODRIGO MIGUEL DOS SANTOS,0000038659290468,cartao_0000038659290468
22,SAMUEL LUIZ FLORÊNCIO CORREA LIMA DE CAS,0000038658961659,cartao_0000038658961659
293,SOPHIA ROCHA DE ANDRADE,0000124556810627,cartao_0000124556810627
12,SÍNTIA NEVES BERNARDES DE LACERDA,0000038663897487,cartao_0000038663897487
13,TAYNARA NOBRE DA SILVA,0000038659155941,cartao_0000038659155941
14,VANESSA CRISTINA DE CASTRO PEREIRA,0000038658961900,cartao_0000038658961900
16,VINÍCIUS CRISPIM COSTA,0000038658961944,cartao_0000038658961944
486,VISITANTE1,0000014307303760,cartao_0000014307303760
487,VISITANTE2,000 014307551553,cartao_000 014307551553
488,VISITANTE3,0000024307304444,cartao_0000024307304444
15,WERITON SILVA DE PAULA,0000038663901457,cartao_0000038663901457

In [37]:
# Vamos atualizar o Banco de Dados local com os dados do DataFrame:

from topsoft.repository import (
    bind_cartao_acesso_to_aluno,
    get_or_create_cartao_acesso,
    get_or_create_aluno,
)

for index, row in not_aluno_df.iterrows():
    cartao_acesso = get_or_create_cartao_acesso(row["cartao"])

    # Convert row to dict and remove NaN values
    dict_row = row.to_dict()
    dict_row = {k: v for k, v in dict_row.items() if pd.notna(v)}
    dict_row = {k: v for k, v in dict_row.items() if v is not None}
    # TODO: We could drop NaN values directly in the DataFrame before iterating, but this is a quick fix.

    # Create or get the aluno, passing all row values as keyword arguments
    aluno = get_or_create_aluno(**dict_row)

    # Bulk update
    bind_cartao_acesso_to_aluno(
        cartao_acesso_id=cartao_acesso.id,
        aluno_id=aluno.id,
    )
    print(f"Cartão {cartao_acesso.numeracao} vinculado ao aluno {aluno.nome}.")

Cartão 0000335012942875 vinculado ao aluno ADAILTON LINO LACERDA.
Cartão 0000038663884438 vinculado ao aluno ANDREIA RODRIGUES DA SILVA.
Cartão 0000004307303760 vinculado ao aluno ANDRÉA MARTINS DE OLIVEIRA.
Cartão 0000038663884449 vinculado ao aluno CÁSSIO SILVA FERREIRA.
Cartão 0000038659043912 vinculado ao aluno DANILO DA PENHA E SILVA.
Cartão 0000038663901480 vinculado ao aluno DEUZELICE PEREIRA DE MATOS.
Cartão 0000124556796581 vinculado ao aluno EDUARDA SILVA SANTOS.
Cartão 0000004307304444 vinculado ao aluno GIOVANNA DE JESUS SANTOS.
Cartão 0000446682931338 vinculado ao aluno IDELMA CARVALHO NOBRE DA SILVA.
Cartão 0000038659047246 vinculado ao aluno IVANI VICENTE DA SILVA.
Cartão 0000038659047261 vinculado ao aluno JORDANA BARRETO GALLETTI.
Cartão 0000038658961692 vinculado ao aluno JOSEFA DE CARVALHO NOBRE.
Cartão 0000038658961867 vinculado ao aluno KAMILA DE JESUS SANTOS.
Cartão 0000004307551553 vinculado ao aluno LUCIANA INÁCIO AMORIM DE ARAUJO.
Cartão 0000355014297670 vinculado ao aluno LUIZ OTAVIO GARCIA SOARES.
Cartão 0000038663969990 vinculado ao aluno MARCELA MOREIRA DE AGUIAR.
Cartão 0000369374783691 vinculado ao aluno MARIA DO SOCORRO ANTUNES MUDESTO.
Cartão 0000038660412590 vinculado ao aluno MARIA DOMINGAS DE FATIMA.
Cartão 0000335012974439 vinculado ao aluno MARIA GLORIA OLIVEIRA COSTA.
Cartão 0000038663880708 vinculado ao aluno MARIA GUIOMAR DURÃES PORTO.
Cartão 0000038663897502 vinculado ao aluno PATRÍCIA PAIXÃO COIMBRA.
Cartão 0000038659290468 vinculado ao aluno RODRIGO MIGUEL DOS SANTOS.
Cartão 0000038658961659 vinculado ao aluno SAMUEL LUIZ FLORÊNCIO CORREA LIMA DE CAS.
Cartão 0000124556810627 vinculado ao aluno SOPHIA ROCHA DE ANDRADE.
Cartão 0000038663897487 vinculado ao aluno SÍNTIA NEVES BERNARDES DE LACERDA.
Cartão 0000038659155941 vinculado ao aluno TAYNARA NOBRE DA SILVA.
Cartão 0000038658961900 vinculado ao aluno VANESSA CRISTINA DE CASTRO PEREIRA.
Cartão 0000038658961944 vinculado ao aluno VINÍCIUS CRISPIM COSTA.
Cartão 0000014307303760 vinculado ao aluno VISITANTE1.
Cartão 000 014307551553 vinculado ao aluno VISITANTE2.
Cartão 0000024307304444 vinculado ao aluno VISITANTE3.
Cartão 0000038663901457 vinculado ao aluno WERITON SILVA DE PAULA.